oci:
  client:
    region: ${OCI_CLI_REGION:fra}
    tenancyId: ${OCI_CLI_TENANCY}
    userId: ${OCI_CLI_USER}
    fingerprint: ${OCI_CLI_FINGERPRINT}
    privateKey: ${OCI_CLI_KEY_CONTENT}
  notification:
    topicId: ocid1.onstopic.oc1.eu-frankfurt-1.amaaaaaabas6vyiamdvbdjqfpkekmvc6mzemc7gsmxcty6wlykauwfzz5tva
    compartmentId: ocid1.compartment.oc1..aaaaaaaa6o6arsldtxyrzyokcuqnsoao6rj7tlhkihlkorgxp42sr56njafq
  ostorage:
    nameSpace: frkogu3mhwjt
    bucketName: invoice_manager_bucket
  queue:
    ocid: ocid1.queue.oc1.eu-frankfurt-1.amaaaaaabas6vyiaodmj6xvsrhossja7lgjggjz6npjb63ejgvaa736xhiva
    dlqOcid: ocid1.queue.oc1.eu-frankfurt-1.amaaaaaabas6vyiaodmj6xvsrhossja7lgjggjz6npjb63ejgvaa736xhiva-dlq
    endpoint: https://cell-1.queue.messaging.eu-frankfurt-1.oci.oraclecloud.com

spring:
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.eu-frankfurt-1.oraclecloud.com))(connect_data=(service_name=ga57d0421d38d7f_invoices_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ADMIN
    password: Qwerty1234567890
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      s-q-l-for-validate-connection: select * from dual
      connection-pool-name: connectionPoolName1
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
