oci:
  client:
    region: ${OCI_CLI_REGION:fra}
    tenancyId: ${OCI_CLI_TENANCY}
    userId: ${OCI_CLI_USER}
    fingerprint: ${OCI_CLI_FINGERPRINT}
    privateKey: ${OCI_CLI_KEY_CONTENT}
  notification:
    topicId: ocid1.onstopic.oc1.eu-frankfurt-1.amaaaaaabas6vyiamdvbdjqfpkekmvc6mzemc7gsmxcty6wlykauwfzz5tva
  ostorage:
    nameSpace: frkogu3mhwjt
    bucketName: invoice_manager_bucket
  queue:
    ocid: ocid1.queue.oc1.eu-frankfurt-1.amaaaaaabas6vyiaodmj6xvsrhossja7lgjggjz6npjb63ejgvaa736xhiva
    dlqOcid: ocid1.queue.oc1.eu-frankfurt-1.amaaaaaabas6vyiaodmj6xvsrhossja7lgjggjz6npjb63ejgvaa736xhiva-dlq
    endpoint: https://cell-1.queue.messaging.eu-frankfurt-1.oci.oraclecloud.com

