name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew clean build

  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: fra.ocir.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fra.ocir.io/dmitrykvartalny/invoice-manager:latest

#  deploy:
#    runs-on: ubuntu-latest
#
#    needs: docker
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Oracle Cloud CLI
#        uses: oracle/oci-cli-action@v2
#        with:
#          config-file: ${{ secrets.OCI_CONFIG_PATH }}
#
#      - name: Deploy to Oracle Cloud
#        run: |
#          # Your deployment script or commands here
#          # Example: oci fn deploy ...
#
## docker tag invoice-manager:latest fra.ocir.io/dmitrykvartalny/invoice-manager:latest
## docker push fra.ocir.io/dmitrykvartalny/invoice-manager:latest
